Add support for GraalVM native serial GC logs
apple/GCGC pull request #8
Opened 2023-08-08 10:42 UTC by galderz

This PR enhances the repository to read the serial GC logs in GraalVM native runtime, SubstrateVM.

It adds:
* Support for reading GraalVM serial GC logs.
* Unit test to verify that the elements are retrieved as expected.

GraalVM's serial GC is stop-the-world, so both the `Incremental GC` and `Full GC` should be considered pauses. To evaluate the data in the `GraalVM.log`, the `pauses_only` method needs to look like this:

```
    def pauses_only(row):
      if "EventType" in row:
          if row["EventType"] == "Pause":
              return True

      if "EventName" in row:
          if row["EventName"] == "Incremental GC" or row["EventName"] == "Full GC":
              return True

    return False
```

Having done that, and analysing the `GraalVM.log` file independently, you get graphs like these:

![STW pauses during program time](https://github.com/apple/GCGC/assets/50187/34070bd3-56d7-43e8-9caf-e20716a1483c)
![STW pauses by Event Name](https://github.com/apple/GCGC/assets/50187/6d26cc7c-a598-4a81-b29d-a9cc4ae23c1f)
![Heap used before GC](https://github.com/apple/GCGC/assets/50187/dd9e34ce-7ef9-421b-9712-98376f2098a3)
![Heap used after GC](https://github.com/apple/GCGC/assets/50187/820a3418-ee89-4d14-9363-43a4d0fe6a63)

The PR does not currently update the notebook because the workload for the sample `GraalVM.log` is not comparable to the workload of the other GC logs. I want to run some tests where I do such a thing and I can compare all, including GraalVM, GC logs. This probably a new dataset, say stored under `datasets/quarkus` and maybe a different notebook to not overwrite existing notebook. Any thoughts on this?

2023-08-08 13:26 UTC, ivankrylov commented
Just a quick note that I noticed the PR and I will get back shortly.

2023-08-10 10:58 UTC, bmathiske commented
I suggest changing method "pauses_only" to this:
```
def pauses_only(row):
    if "EventType" in row:
        if row["EventType"] == "Pause" or row["EventName"] == "Incremental GC" or row["EventName"] == "Full GC":
          return True
    return False 
```
Then users only need to change the input files and labels and have the existing notebook running for them in no time.

2023-08-10 11:01 UTC, bmathiske requested changes

2023-08-10 11:01 UTC, bmathiske commented on src/parse_log_file.py
>                                          # 123541.21425
```suggestion
                                      # 123541.21425
```

2023-08-10 11:01 UTC, bmathiske commented on src/parse_log_file.py
> +                                                                       # 9999K
```suggestion
                                                                # 9999K
```

2023-08-10 11:01 UTC, bmathiske commented on src/parse_log_file.py
> +                                                                         # ->9999K
```suggestion
                                                                  # ->9999K
```

2023-08-10 11:01 UTC, bmathiske commented on src/parse_log_file.py
> +                                                                     # 0.0 secs
```suggestion
                                                                      # 0.0 secs
```

2023-08-10 11:01 UTC, bmathiske commented on src/read_log_file.py
> +
```suggestion
```

2023-08-10 11:01 UTC, bmathiske commented on src/read_log_file.py
> +
```suggestion
```

2023-08-10 11:01 UTC, bmathiske commented on src/read_log_file.py
> +
```suggestion
```

2023-08-10 11:01 UTC, bmathiske commented on src/read_log_file.py
> +
```suggestion
```

2023-08-10 11:01 UTC, bmathiske commented on src/read_log_file.py
> +
```suggestion
```

2023-08-10 11:01 UTC, bmathiske commented on src/read_log_file.py
> +
Some methods have separating blank lines and another doesn't. I suggest using one of these styles uniformly. To better identify where a method starts and ends I am going without blank lines here. (If needed, in larger methods than these, one could insert almost blank lines with an empty '#' comment.)

2023-08-10 11:01 UTC, bmathiske commented on src/read_log_file.py
> +def scale_heap_units(df):
Observing no blank lines here - see above.

2023-08-10 12:35 UTC, ivankrylov commented
Hi @galderz , thank you so much for the contribution. 
As for the file: datasets/graalvm_log_file_test.log - can you kindly specify what version of GraalVM is used? Perhaps you could factor this file into a separate commit and specify in a commit message how this snipped is produced.

2023-08-14 07:58 UTC, galderz commented
> As for the file: datasets/graalvm_log_file_test.log - can you kindly specify what version of GraalVM is used? Perhaps you could factor this file into a separate commit and specify in a commit message how this snipped is produced.

Fair enough. I'll look into it. I'll try to do the same with the existing `GraalVM.log` file, even though this one might change in the future as noted in the description.

2023-09-12 08:58 UTC, ivankrylov commented
I am back from a somewhat long vacation. Let's drive this PR to integration. Can you factor the same vm go from GraalVm into a separate commit with a commit message that tells how exactly a log was produced? You can use any java app freely available to generate a log: a pet clinic app or simple app from a demo directory in Java 8 distributions.

2023-09-12 12:54 UTC, ivankrylov commented
All right, I will take the change as is and address the remaining issues ourselves. 
@galderz Thank you so much for your contribution, keep them coming!

2023-09-12 12:54 UTC, merged

2023-09-13 07:27 UTC, galderz commented
Hey @ivankrylov, thanks for integrating this!

Sorry I've not provided an update since last month. I've been working on some benchmarking and I was hoping to extract some GraalVM GC log out of it eventually for roughly a period of 5 minutes (that seems to be the period for the logs in the repo). However, some other things have come my way.

Also, the GC log output is changing in GraalVM for JDK 21 (to be released next week), so I'll send a separate PR to update the GC parsing logic to adjust for that version, and will use the opportunity to send a GC log that contains more interesting data.

2023-09-13 07:55 UTC, ivankrylov commented
Sounds good @galderz! Looking forward for your next PR. This would also be a good chance to clear up in-the-sources notes on how GraalVM gc logs are generated (GraalVM version, test app name).